export const htmlData = {
    componentName:'elMain', 
    class:['accountList','container'],
    resizeMethod:'onResize',
    childrenNode:[
      {
        componentName:'elForm', 
        class:['searchForm','searchUser'],
        childrenNode:[
          {
            componentName:'elContainer', 
            class:['search-left'],
            childrenNode:[
              {
                componentName:'elFormItem', 
                label:'form.sorting',
                prop:'',
                childrenNode:[
                  {
                    componentName:'elInput', 
                    paramsName:'searchForm',
                    vModel:'orderNum',
                    placeholder:['placeholder.pleaseEnter','form.sorting'],
                    clearable:true
                  }
                ]
              },
              {
                componentName:'elFormItem', 
                label:'form.searchReferenceName',
                prop:'',
                childrenNode:[
                  {
                    componentName:'elLevelSelect', 
                    paramsName:'searchForm',
                    vModel:'referenceName',
                    placeholder:['placeholder.pleaseSelect','persion.problemCategory'],
                    clearable:true,
                    elOptionList:'levelSelectList',
                  }
                ]
              },
              {
                componentName:'elFormItem', 
                label:'',
                prop:'',
                childrenNode:[
                  {
                    componentName:'elButton', 
                    class:['addAccountBtn'],
                    event:'addContent',
                    icon:'el-icon-plus',
                    title:['form.add']
                  }
                ]
              },
            ]
          },
          {
            componentName:'elContainer',
            class:['search-right'],
            childrenNode:[
              {
                componentName:'elFormItem', 
                label:'',
                prop:'',
                childrenNode:[
                  {
                    componentName:'elButton', 
                    class:['mic-btn-primary','searchAccount'],
                    event:'queryList',
                    icon:'',
                    title:['form.query']
                  }
                ]
              },
            ]  
          }
        ]
      },
      {
        componentName:'elTable', 
        class:['accountTable'],
        tableDataName:'tableData',
        tableHeightName:'tableHeight',
        refName:'multipleTable',
        tooltipEffect:'dark',
        stripe:true,
        style:'width: 100%;margin-bottom: 20px;',
        rowKey:'id',
        defaultSort:{prop: 'orderNum', order: 'ascending'},
        defaultExpandAll:true,
        treeProp:{children: 'childrenNode', hasChildren: 'hasChildren'},
        childrenNode:[
          
            {
              componentName:'elTableColumn', 
              type:'',
              label:'table.operation',
              slotScope:true,
              width:'260',
              formatDate:false,
              align:'center',
              operation:true,
              childrenNode:[
                {
                  componentName:'elButton',
                  class:['editBtn'],
                  event:'editContent',
                  icon:'',
                  row:true,
                  tableParams:true,
                  title:['form.edit'],
                  btnType:'text',
                  btnCondition:'title.i18n_title'
                },
                {
                  componentName:'elButton',
                  class:['delBtn'],
                  event:'delHandle',
                  icon:'',
                  row:true,
                  tableParams:true,
                  title:['form.delete'],
                  btnType:'text',
                  btnCondition:'title.i18n_title'
                }
  
              ]
            },
            
            {
              componentName:'elTableColumn', 
              type:'',
              label:'pageRule.componentName',
              slotScope:true,
              value:'componentName',
              width:''
            },
            {
              componentName:'elTableColumn', 
              type:'',
              label:'pageRule.attributeName',
              slotScope:true,
              value:'attributeName',
              width:''
            },
            {
              componentName:'elTableColumn', 
              type:'',
              label:'pageRule.attributeType',
              slotScope:true,
              value:'attributeType',
              width:''
            },
            
            {
              componentName:'elTableColumn', 
              type:'',
              label:'pageRule.attributeLabel',
              slotScope:true,
              value:'attributeLabel',
              width:''
            },
            {
              componentName:'elTableColumn', 
              type:'',
              label:'pageRule.attributeModel',
              slotScope:true,
              value:'attributeModel',
              width:''
            }
          ]  
      },
      {
        componentName:'elPagination', 
        total: 0,
        size: 10,
        current: 1,
        class:['account-bottom'],
        params:'pageAttribute',
        layout:'prev, pager, next',
        pageSize:[10, 20, 50, 100],
        className:["account-bottom"],
        sizeChangeName:'handleSizeChange',
        currentChangeName:'handleCurrentChange'
      },
      {
        componentName:'elDialog', 
        /*
        title:{
          edit:['form.add','form.content'],
          add:['form.edit','form.content']
        },
        */
        title:['form.add'],
        width:'850px',
        dialogShowName:'addContentDialog',
        condition:'editMethodUser',
        closeMethodName:'handleClose',
        center:true,
        childrenNode:[
          {
            componentName:'elForm', 
            class:[],
            model:'paramsData',
            formRule:'paramsDataRules',
            labelWidth:'230px',
            upladRef:'uploadFile',
            refName:'paramsDataRef',
            slotList:[{slotName:'moduleUploadSearchSlot',name:'moduleUploadSlot'}],
            childrenNode:[
              {
                componentName:'elContainer', 
                class:['helpInfo'],
                refName:'helpInfo',
                childrenNode:[
                  {
                    componentName:'elFormItem',
                    label:'pageRule.componentType',
                    prop:'',
                    elFormItemCondition:'editMethodUser',
                    childrenNode:[
                      {
                        componentName:'elLevelSelect', 
                        vModel:'paramsData.componentType',
                        label:'pageRule.componentType',
                        autocomplete:'',
                        placeholder:['placeholder.pleaseSelect','pageRule.componentType'],
                        clearable:true,
                        elOptionList:'levelSelectList',
                      }
                    ]
                  },
                  {
                    componentName:'elFormItem', 
                    label:'pageRule.componentName',
                    prop:'',
                    childrenNode:[
                      {
                        componentName:'elInput', 
                        inputCondition:'editMethodUser',
                        vModel:'paramsData.componentName',
                        label:'form.componentName',
                        prop:'',
                        autocomplete:'off',
                        placeholder:['placeholder.pleaseEnter','pageRule.componentName'],
                        clearable:true
                      }
                    ]
                  },
                  {
                    componentName:'elFormItem',
                    label:'pageRule.attributeName',
                    prop:'attributeName',
                    childrenNode:[
                      {
                        componentName:'elInput', 
                        inputCondition:'editMethodUser',
                        vModel:'paramsData.attributeName',
                        label:'pageRule.attributeName',
                        prop:'attributeName',
                        autocomplete:'off',
                        placeholder:['placeholder.pleaseEnter','pageRule.attributeName'],
                        clearable:true
                      }
                    ]
                  },
                  {
                    componentName:'elFormItem', 
                    label:'pageRule.attributeType',
                    prop:'attributeType',
                    childrenNode:[
                      {
                        componentName:'elInput', 
                        inputCondition:'editMethodUser',
                        vModel:'paramsData.attributeType',
                        label:'pageRule.attributeType',
                        prop:'attributeType',
                        autocomplete:'off',
                        placeholder:['placeholder.pleaseEnter','pageRule.attributeType'],
                        clearable:true
                      }
                    ]
                  },

                  {
                    componentName:'elFormItem', 
                    label:'pageRule.attributeLabel',
                    prop:'attributeLabel',
                    childrenNode:[
                      {
                        componentName:'elInput', 
                        vModel:'paramsData.attributeLabel',
                        label:'pageRule.attributeLabel',
                        prop:'attributeLabel',
                        autocomplete:'off',
                        placeholder:['placeholder.pleaseEnter','pageRule.attributeLabel'],
                        clearable:true
                      }
                    ]
                  },

                  {
                    componentName:'elFormItem', 
                    label:'pageRule.attributeModel',
                    prop:'attributeModel',
                    childrenNode:[
                      {
                        componentName:'elInput', 
                        vModel:'paramsData.attributeModel',
                        label:'pageRule.attributeModel',
                        prop:'attributeModel',
                        autocomplete:'off',
                        placeholder:['placeholder.pleaseEnter','pageRule.attributeModel'],
                        clearable:true
                      }
                    ]
                  }
                ]  
              },
              {
                componentName:'elContainer', 
                class:['dialog-footer'],
                ref:'',
                childrenNode:[{
                    componentName:'elFormItem',
                    label:'',
                    prop:'',
                    childrenNode:[
                      {
                        componentName:'elButton', 
                        class:['el-button--default'],
                        event:'resetForm',
                        icon:'',
                        params:true,
                        paramsName:'paramsDataRef',
                        elFormStatus:'resetFieldStatus',
                        title:['form.cancel'],
                        ref:'paramsData'
                      },
                      {
                        componentName:'elButton', 
                        class:['saveMethodList'],
                        btnType:'primary',
                        event:'submitForm',
                        icon:'',
                        params:true,
                        elFormStatus:'resetFieldStatus',
                        paramsName:'paramsDataRef',
                        title:['form.save']
                      }
                    ]  
                }]    
              }
            ]
          }
        ]
      }
    ]
  }
